### ISSUE TITLE
Possibly publish attendee list before event?

### ISSUE THREAD

**Issue by cvan** [w3c/vr-workshop#12]
Lots of amazing people in the Web and VR fields have expressed interest. It's awesome!

I know of the URL for the results from the VR workshop registration forms and position statements, etc. But, could/should we make the list public? We could hide personal info. (though I didn't see much/any).

I thought about turning the RSVP list into a [Google Sheets document](https://docs.google.com/spreadsheets/), but I figured I'd ask y'all first.

For Meetup.com, they publish the [attendee list](https://www.meetup.com/Silicon-Valley-HTML5-WebGL-Meetup/events/233962262/) (with photos and links to their Meetup.com profiles). I can imagine seeing the attendee list might help get more people express interest in attending (though I know registration is closed off) and might also help get more attention about the Workshop.

@dontcallmedom, @anssiko - thoughts?

**Comment by anssiko** [comment]
The registration form said "The results of this questionnaire are available to anybody." so publishing the list more prominently should not be an issue. Simplest solution would be to add a "see who's registered" link to the workshop page pointing to the current list.

@dontcallmedom on a related note, should we open a late registration for a limited time?

PRs welcome :-)

**Comment by cvan** [comment]
> @dontcallmedom on a related note, should we open a late registration for a limited time?

I was just going to contact you both about that. can we extend the registration by say a week? And, let's tweet about it and circulate that info so people know the exact date/time of the deadline. That sound okay? I'm sensing some more attention lately now that more info. on the Workshop has been spread.
