### ISSUE TITLE
Consider using Google Forms instead of W3C Registration form

### ISSUE THREAD

**Issue by cvan** [w3c/vr-workshop#20]
Do y'all  think we could use an anonymous simple Google Forms form - instead of having to create an account and express interest to be invited to attend?

**Comment by dontcallmedom** [comment]
There is no need for an account to fill the W3C expression of interest form, and registration is closing tonight in any case, so I wouldn't set up a new system at this point in time.

(note that Google Forms are not without issue — e.g. some companies prevent their use, and some countries block access to Google products)
