### ISSUE TITLE
Consider removing "position statement" from main Workshop page

### ISSUE THREAD

**Issue by cvan** [w3c/vr-workshop#7]
I'm not too familiar with W3C protocol, but IMO the concept of submitting a "registration form" _or_ a "position statement" is confusing. If folks can express interest in attending by simply registering, I'm not sure who would bother to submit a position statement.

I think perhaps rephrasing things to "submit a presentation" and loosening the requirements could go a long way. A 500-1000 word requirement isn't nothing either. I understand the limited space of the venue, but I think the length and verbosity of the copy on the Workshop page is only increasing friction and decreasing interest in what should be an inviting welcome to a workshop on the Web & VR.

**Comment by dontcallmedom** [comment]
I think this was handled in #9, so closing
