### ISSUE TITLE
Set deadline for sponsorship

### ISSUE THREAD

**Issue by cvan** [w3c/vr-workshop#8]
On the [Sponsorship Packages page](https://w3c.github.io/vr-workshop/sponsorship.html), the [month and date are missing](https://github.com/w3c/vr-workshop/blob/25b5e90/sponsorship.html#L198):

<img width="410" alt="screen shot 2016-09-22 at 3 51 42 am" src="https://cloud.githubusercontent.com/assets/203725/18745674/f9100aca-8077-11e6-8ffa-ebc35ae2df43.png">

Which date should we set as the deadline for sponsorship?

**Comment by cvan** [comment]
@dontcallmedom @anssiko when's the deadline, do you think? do we want to close off sponsorships? I assume not just yet.

**Comment by dontcallmedom** [comment]
I've been trying (so far unsuccessfully) to get a clear answer to that question; but I'll update the page as soon as I get it.
